spring:
  application:
    name: calculator-back

# Actuator endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: [ info, health ]

server:
  port: 8080

auditable: true