springdoc:
  show-actuator: true
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
    
  datasource:
    testOnBorrow: 'true'
    validationQuery: SELECT 1
    url: jdbc:h2:mem:test
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: public
        temp:
          use_jdbc_metadata_defaults: 'false'
    hibernate:
      ddl-auto: validate
    show-sql: 'true'

    
  main:
    banner-mode: 'console'
    
auditable: true


